version: '3.5'

services:
  db:
    container_name: nivea-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: nivea_db
      MYSQL_USER: nivea_database
      MYSQL_PASSWORD: mbx12345
      MYSQL_ROOT_PASSWORD: mbx12345
  phpmyadmin:
    container_name: nivea-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - '1234:1234'
    environment:
      MYSQL_USER: nivea_database
      MYSQL_PASSWORD: mbx12345
      MYSQL_ROOT_PASSWORD: mbx12345
  api:
    container_name: nivea-api
    image: nivea-api
    build:
      context: .
      dockerfile: ./rewards-api/Dockerfile
    volumes:
      - '.:/src'
      - '/src/node_modules'
    ports:
      - '80:4000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true